### PR TITLE
Fixing tests and loader utils

### PR DESCRIPTION
**Pull request by chrisdothtml**
- fixing a few issues I ran into when trying to run unit tests
- using `loaderUtils.getOptions` instead of `loaderUtils.parseQuery`

### CODE REVIEW

**Comment by chrisdothtml** [comment]
PRs are apparently ignored for this repo

**Comment by millette** [comment]
@chrisdothtml Give it a bit of time to account for the holidays :-)

I just had a response on riot-cli, keep the faith!

**Comment by millette** [comment]
Pinging @GianlucaGuarini just in case.

**Comment by GianlucaGuarini** [comment]
v2.0.0 has fixed already all these issues but thank you anyway

**Pull request closed without merging**
