### PR TITLE
Fix loaderUtils.parseQuery() deprecation warning

### LINKED ISSUE #3: Deprecation Warning: loaderUtils.parseQuery()
Just getting around to upgrading from Riot 2.x and Webpack 1.x and switching from riotjs-loader to the official one. I'm getting this warning during builds now:

> loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Everything is working fine despite the warning - thought I'd let you guys know just in case.

### PR DESCRIPTION
**Pull request by Stubb0rn**
Fixes #3

I couldn't get existing tests to work, there was a large difference between generated bundles and saved fixtures in master branch. So, in order to proceed with changes required for loaderUtils issue, I had to simplify test setup to test only loader output without whole webpack bundle context.

### CODE REVIEW

**Comment by wagerfield** [comment]
Could this get merged please?

**Comment by Stubb0rn** [comment]
I would like to get at least some feedback for this PR. I might be able to split it in 2 parts (test updates and deprecation fix) if necessary.

**Comment by gshegosh** [comment]
What can I do to help with this PR?
I'd love to see it merged, because the deprecation warning says it's going to stop working at all in next webpack release.

**Comment by racquetmaster** [comment]
+1

**Comment by GianlucaGuarini** [comment]
thank you it was fixed in v1.1.3 and v2.0.0

**Pull request closed without merging**
